### PR TITLE
feat: Return number of bytes written for every operation

### PR DESCRIPTION
**Pull request by matheus23**
The main change is to return `usize` from `CarWriter::write` and `CarWriter::write_header`. These `usize`s indicate the amount of bytes written to the underlying `AsyncWrite`.

Knowing these numbers is useful to us (at fission), since it allows us to package up car files "until at least X bytes were written into the CAR file".

I added a proptest to make sure that the final CAR file is just as big as all the returned `usize`s summed up. (I initially messed up the impl. `proptest` makes stuff like this easy to fix though.)

### CODE REVIEW

**Review by dignifiedquire — APPROVED** [review]
nice

**Comment by dignifiedquire** [comment]
sigh wasm builds are broken

**Comment by matheus23** [comment]
> sigh wasm builds are broken

Is that on me? `cargo build --target wasm32-unknown-unknown` works for me locally.

I saw there's some failures due to 1.63 being the MSRV, not 1.60 anymore. I pushed a commit that pushes the MSRV to 1.63.

**Comment by dignifiedquire** [comment]
wasn’t you, lets see if your fix helps

**Comment by matheus23** [comment]
Ah I vaguely remembered seeing something related recently in rs-ucan. Followed the traces back and found this:
https://github.com/subconsciousnetwork/noosphere/pull/514

Similar changes will probably fix this here, too. Let me commit them real quick.

**Comment by matheus23** [comment]
I think this should be ready to merge :v:

**Comment by matheus23** [comment]
I ran CI on my fork, it's [running through fine there](https://github.com/matheus23/iroh-car/pull/2). I swear I'm done done for good now.

**Review by dignifiedquire — APPROVED** [review]

**Comment by matheus23** [comment]
:tada:

**Comment by dignifiedquire** [comment]
published in `0.4.0`

**Pull request merged**
